# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'bluebikeshop-conn'
    subscriptionId: 'fe82accc-f7cc-466f-9efe-1fd0143c3e57'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'bluebikeshop001-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/norregaard/BlueBikeShop-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectname BlueBikeShop'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
